# Generated by Django 3.2.23 on 2024-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placecarrent',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
