# Generated by Django 3.2.23 on 2024-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(blank=True, upload_to='cars_image')),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_rate', models.IntegerField(blank=True, null=True)),
                ('car_rate_with_km', models.IntegerField(blank=True, null=True)),
                ('car_passenger', models.IntegerField(blank=True, null=True)),
                ('air_conditioner', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'cars_rent',
            },
        ),
    ]
