# Generated by Django 3.2.23 on 2024-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_and_rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsrent',
            name='show_car',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
